# Generated by Django 4.1.7 on 2023-03-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productcategory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
