# Generated by Django 4.1.7 on 2023-03-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOrder',
            new_name='ProductInOrder',
        ),
    ]
