# Generated by Django 4.1.7 on 2023-03-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer_address_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар у заказі', 'verbose_name_plural': 'Товари у заказі'},
        ),
    ]
