# Generated by Django 4.1.7 on 2023-03-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_charecters'),
        ('orders', '0007_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productimage'),
        ),
    ]
