# Generated by Django 4.1.7 on 2023-03-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='charecters',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
